/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pipesim;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author kogayou
 */
public class MainJFrame extends javax.swing.JFrame implements ActionListener {
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        jButton1.setEnabled(false);
        jRun.setEnabled(false);
        jPause.setEnabled(false);
        jStep.setEnabled(false);
        jReset.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jW_stat = new javax.swing.JLabel();
        jW_icode = new javax.swing.JLabel();
        jW_valE = new javax.swing.JLabel();
        jW_valM = new javax.swing.JLabel();
        jW_dstE = new javax.swing.JLabel();
        jW_dstM = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jM_stat = new javax.swing.JLabel();
        jM_icode = new javax.swing.JLabel();
        jM_Cnd = new javax.swing.JLabel();
        jM_valE = new javax.swing.JLabel();
        jM_valA = new javax.swing.JLabel();
        jM_dstE = new javax.swing.JLabel();
        jM_dstM = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jE_stat = new javax.swing.JLabel();
        jE_valA = new javax.swing.JLabel();
        jE_valC = new javax.swing.JLabel();
        jE_ifun = new javax.swing.JLabel();
        jE_icode = new javax.swing.JLabel();
        jE_dstM = new javax.swing.JLabel();
        jE_dstE = new javax.swing.JLabel();
        jE_valB = new javax.swing.JLabel();
        jE_srcA = new javax.swing.JLabel();
        jE_srcB = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jD_stat = new javax.swing.JLabel();
        jD_icode = new javax.swing.JLabel();
        jD_ifun = new javax.swing.JLabel();
        jD_rA = new javax.swing.JLabel();
        jD_rB = new javax.swing.JLabel();
        jD_valC = new javax.swing.JLabel();
        jD_valP = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jF_stat = new javax.swing.JLabel();
        jF_predPC = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jeax = new javax.swing.JLabel();
        jecx = new javax.swing.JLabel();
        jedx = new javax.swing.JLabel();
        jebx = new javax.swing.JLabel();
        jedi = new javax.swing.JLabel();
        jebp = new javax.swing.JLabel();
        jesi = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jesp = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jZF = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jSF = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jOF = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jcycle = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jinstruction = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jCPI = new javax.swing.JLabel();
        jPC = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jStep = new javax.swing.JButton();
        jRun = new javax.swing.JButton();
        jPause = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel1.setText("         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setAlignmentY(0.0F);

        jLabel2.setText("跳转至");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setText("0x");

        jTextField1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("W:");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("icode");

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("valE");

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("valM");

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("dstE");

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setText("dstM");

        jW_stat.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jW_stat.setForeground(new java.awt.Color(204, 0, 204));
        jW_stat.setText("AOK");

        jW_icode.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jW_icode.setForeground(new java.awt.Color(204, 0, 204));
        jW_icode.setText("0");

        jW_valE.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jW_valE.setForeground(new java.awt.Color(204, 0, 204));
        jW_valE.setText("0x00000000");

        jW_valM.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jW_valM.setForeground(new java.awt.Color(204, 0, 204));
        jW_valM.setText("0x00000000");

        jW_dstE.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jW_dstE.setForeground(new java.awt.Color(204, 0, 204));
        jW_dstE.setText("none");

        jW_dstM.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jW_dstM.setForeground(new java.awt.Color(204, 0, 204));
        jW_dstM.setText("none");

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("M:");

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("icode");

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Cnd");

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("valE");

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("valA");

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("dstE");

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("dstM");

        jM_stat.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_stat.setForeground(new java.awt.Color(255, 102, 0));
        jM_stat.setText("AOK");

        jM_icode.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_icode.setForeground(new java.awt.Color(255, 102, 0));
        jM_icode.setText("0");

        jM_Cnd.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_Cnd.setForeground(new java.awt.Color(255, 102, 0));
        jM_Cnd.setText("0");

        jM_valE.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_valE.setForeground(new java.awt.Color(255, 102, 0));
        jM_valE.setText("0x00000000");

        jM_valA.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_valA.setForeground(new java.awt.Color(255, 102, 0));
        jM_valA.setText("0x00000000");

        jM_dstE.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_dstE.setForeground(new java.awt.Color(255, 102, 0));
        jM_dstE.setText("none");

        jM_dstM.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jM_dstM.setForeground(new java.awt.Color(255, 102, 0));
        jM_dstM.setText("none");

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 0));
        jLabel17.setText("valC");

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 0));
        jLabel18.setText("valA");

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 153, 0));
        jLabel19.setText("icode");

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 153, 0));
        jLabel20.setText("ifun");

        jLabel21.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 153, 0));
        jLabel21.setText("dstE");

        jLabel22.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 153, 0));
        jLabel22.setText("dstM");

        jLabel23.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 153, 0));
        jLabel23.setText("E:");

        jLabel24.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 153, 0));
        jLabel24.setText("valB");

        jLabel25.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 153, 0));
        jLabel25.setText("srcB");

        jLabel26.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 153, 0));
        jLabel26.setText("srcA");

        jE_stat.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_stat.setForeground(new java.awt.Color(51, 153, 0));
        jE_stat.setText("AOK");

        jE_valA.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_valA.setForeground(new java.awt.Color(51, 153, 0));
        jE_valA.setText("0x00000000");

        jE_valC.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_valC.setForeground(new java.awt.Color(51, 153, 0));
        jE_valC.setText("0x00000000");

        jE_ifun.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_ifun.setForeground(new java.awt.Color(51, 153, 0));
        jE_ifun.setText("0");

        jE_icode.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_icode.setForeground(new java.awt.Color(51, 153, 0));
        jE_icode.setText("0");

        jE_dstM.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_dstM.setForeground(new java.awt.Color(51, 153, 0));
        jE_dstM.setText("none");

        jE_dstE.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_dstE.setForeground(new java.awt.Color(51, 153, 0));
        jE_dstE.setText("none");

        jE_valB.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_valB.setForeground(new java.awt.Color(51, 153, 0));
        jE_valB.setText("0x00000000");

        jE_srcA.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_srcA.setForeground(new java.awt.Color(51, 153, 0));
        jE_srcA.setText("none");

        jE_srcB.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jE_srcB.setForeground(new java.awt.Color(51, 153, 0));
        jE_srcB.setText("none");

        jLabel27.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setText("D:");

        jLabel28.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("icode");

        jLabel29.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("ifun");

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 255));
        jLabel30.setText("rA");

        jLabel31.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setText("rB");

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("valC");

        jLabel40.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 255));
        jLabel40.setText("valP");

        jD_stat.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_stat.setForeground(new java.awt.Color(0, 0, 255));
        jD_stat.setText("AOK");

        jD_icode.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_icode.setForeground(new java.awt.Color(0, 0, 255));
        jD_icode.setText("0");

        jD_ifun.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_ifun.setForeground(new java.awt.Color(0, 0, 255));
        jD_ifun.setText("0");

        jD_rA.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_rA.setForeground(new java.awt.Color(0, 0, 255));
        jD_rA.setText("none");

        jD_rB.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_rB.setForeground(new java.awt.Color(0, 0, 255));
        jD_rB.setText("none");

        jD_valC.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_valC.setForeground(new java.awt.Color(0, 0, 255));
        jD_valC.setText("0x00000000");

        jD_valP.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jD_valP.setForeground(new java.awt.Color(0, 0, 255));
        jD_valP.setText("0x00000000");

        jLabel33.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("F:");

        jLabel34.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("predPC");

        jF_stat.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jF_stat.setForeground(new java.awt.Color(255, 0, 0));
        jF_stat.setText("AOK");

        jF_predPC.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jF_predPC.setForeground(new java.awt.Color(255, 0, 0));
        jF_predPC.setText("0x00000000");

        jLabel37.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel37.setText("%eax");

        jLabel38.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel38.setText("%ecx");

        jLabel39.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel39.setText("%edx");

        jLabel41.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel41.setText("%ebx");

        jeax.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jeax.setText("0x00000000");

        jecx.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jecx.setText("0x00000000");

        jedx.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jedx.setText("0x00000000");

        jebx.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jebx.setText("0x00000000");

        jedi.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jedi.setText("0x00000000");

        jebp.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jebp.setText("0x00000000");

        jesi.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jesi.setText("0x00000000");

        jLabel49.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel49.setText("%edi");

        jesp.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jesp.setText("0x00000000");

        jLabel51.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel51.setText("%ebp");

        jLabel52.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel52.setText("%esi");

        jLabel53.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel53.setText("%esp");

        jLabel54.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel54.setText("ZF");

        jZF.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jZF.setText("0");

        jLabel56.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel56.setText("SF");

        jSF.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jSF.setText("0");

        jLabel58.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel58.setText("OF");

        jOF.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jOF.setText("0");

        jLabel60.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel60.setText("Cycles");

        jcycle.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jcycle.setText("0");

        jLabel62.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel62.setText("Instructions");

        jinstruction.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jinstruction.setText("0");

        jLabel64.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel64.setText("CPI");

        jCPI.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jCPI.setText("N/A");

        jPC.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        jPC.setText("0x00000000");

        jLabel68.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jLabel68.setText("PC");

        jStep.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jStep.setText("Step");
        jStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStepActionPerformed(evt);
            }
        });

        jRun.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jRun.setText("Run");
        jRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRunActionPerformed(evt);
            }
        });

        jPause.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPause.setText("Pause");
        jPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPauseActionPerformed(evt);
            }
        });

        jReset.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1Hz", "2Hz", "5Hz", "10Hz" }));

        jMenu1.setText("菜单");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        jMenuItem1.setText("载入Y86指令");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        jMenuItem2.setText("退出");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jW_stat)
                                            .addComponent(jM_stat)
                                            .addComponent(jLabel23)
                                            .addComponent(jE_stat)
                                            .addComponent(jLabel27))
                                        .addComponent(jD_stat)
                                        .addComponent(jF_stat)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel41))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel68)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jLabel5))
                                                .addComponent(jLabel11))
                                            .addGap(106, 106, 106)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel14)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel19)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(19, 19, 19)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel34)
                                                                .addComponent(jD_icode)
                                                                .addComponent(jE_icode))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jE_ifun)
                                                        .addComponent(jD_ifun))
                                                    .addGap(25, 25, 25))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(19, 19, 19)
                                                    .addComponent(jM_icode)
                                                    .addGap(43, 43, 43)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel29)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(10, 10, 10)
                                                            .addComponent(jM_Cnd)))
                                                    .addGap(8, 8, 8)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(jLabel17))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(27, 27, 27)
                                                    .addComponent(jLabel30)
                                                    .addGap(35, 35, 35)
                                                    .addComponent(jLabel31))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(17, 17, 17)
                                                    .addComponent(jM_valE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jD_rA)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jD_rB))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jE_valC)))))
                                        .addComponent(jLabel28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jW_icode)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jW_valE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jM_valA)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jE_valA)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jE_valB))
                                                    .addComponent(jW_valM)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jD_valC)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jD_valP)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jStep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                                .addComponent(jRun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel32)
                                                .addGap(77, 77, 77)
                                                .addComponent(jLabel40)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel24)
                                                .addGap(46, 46, 46))
                                            .addComponent(jLabel13)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPC)
                                    .addComponent(jF_predPC)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jeax)
                                            .addComponent(jecx)
                                            .addComponent(jedx)
                                            .addComponent(jebx))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel51)
                                            .addComponent(jLabel52)
                                            .addComponent(jLabel49))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jesp)
                                            .addComponent(jebp)
                                            .addComponent(jesi)
                                            .addComponent(jedi))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel54)
                                                .addGap(18, 18, 18)
                                                .addComponent(jZF))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel56)
                                                .addGap(18, 18, 18)
                                                .addComponent(jSF))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel58)
                                                .addGap(18, 18, 18)
                                                .addComponent(jOF)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jE_dstE)
                            .addComponent(jLabel21)
                            .addComponent(jM_dstE)
                            .addComponent(jLabel15)
                            .addComponent(jW_dstE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jM_dstM)
                                        .addComponent(jLabel22)
                                        .addComponent(jE_dstM)
                                        .addComponent(jW_dstM))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(jE_srcA))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jE_srcB)
                                        .addComponent(jLabel25))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addGap(18, 18, 18)
                                .addComponent(jcycle))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPause, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel64)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel62))
                                .addGap(18, 18, 18)
                                .addComponent(jinstruction)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(340, 340, 340)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jW_stat)
                                    .addComponent(jW_icode)
                                    .addComponent(jW_valE)
                                    .addComponent(jW_valM)
                                    .addComponent(jW_dstE)
                                    .addComponent(jW_dstM))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jM_stat)
                                            .addComponent(jM_icode)
                                            .addComponent(jM_Cnd)
                                            .addComponent(jM_valE)
                                            .addComponent(jM_valA)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jM_dstE)
                                            .addComponent(jM_dstM))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel24)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jE_icode)
                                    .addComponent(jE_stat)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jE_valC)
                                        .addComponent(jE_valA)
                                        .addComponent(jE_valB)
                                        .addComponent(jE_dstE)
                                        .addComponent(jE_dstM))
                                    .addComponent(jE_ifun)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jE_srcA)
                                        .addComponent(jE_srcB)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel28)
                                                .addComponent(jLabel29)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel30))
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel32))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jD_icode)
                                            .addComponent(jD_stat)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jD_rA)
                                                .addComponent(jD_rB)
                                                .addComponent(jD_valC)
                                                .addComponent(jD_valP))
                                            .addComponent(jD_ifun)))
                                    .addComponent(jLabel40))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jF_stat)
                                    .addComponent(jF_predPC))))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel53)
                                        .addComponent(jesp)
                                        .addComponent(jLabel54)
                                        .addComponent(jZF)
                                        .addComponent(jLabel60)
                                        .addComponent(jcycle))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel51)
                                        .addComponent(jebp)
                                        .addComponent(jLabel56)
                                        .addComponent(jSF)
                                        .addComponent(jLabel62)
                                        .addComponent(jinstruction))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel52)
                                        .addComponent(jesi)
                                        .addComponent(jLabel58)
                                        .addComponent(jOF)
                                        .addComponent(jLabel64)
                                        .addComponent(jCPI))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel49)
                                        .addComponent(jedi))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRun)
                                        .addComponent(jPause)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jStep)
                                        .addComponent(jReset)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel37)
                                        .addComponent(jeax))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel38)
                                        .addComponent(jecx))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel39)
                                        .addComponent(jedx))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel41)
                                        .addComponent(jebx))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jPC)
                                        .addComponent(jLabel68)))))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int focusedMemory;
    private int focusedCode;
    private Timer time;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       JFileChooser jFileChooser1=new JFileChooser();
       if (jFileChooser1.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
       {
            Assembler.inputFile=jFileChooser1.getSelectedFile();
            try
            {
                if (!Assembler.assemble())
                {
                    JOptionPane.showMessageDialog(this,Assembler.errorMessage,"载入Y86代码出错",JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            catch (Exception ex)
            {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            focusedMemory=0;
            Core.isOver=false;
            jRun.setEnabled(true);
            jPause.setEnabled(false);
            jStep.setEnabled(true);
            jReset.setEnabled(true);
            Core.reset();
            showCode();
            showMemory();  
            display();
       }       

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int tmp;
        try
        {
            tmp=Integer.parseInt(jTextField1.getText(),16);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"不合法的内存地址","内存跳转出错",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tmp<0||tmp>Core.maxMemory)
        {
            JOptionPane.showMessageDialog(this,"内存地址超出范围","内存跳转出错",JOptionPane.ERROR_MESSAGE);
            return;
        }
        focusedMemory=tmp/16*56;
        jTextArea1.setSelectionStart(focusedMemory);
        jTextArea1.setSelectionEnd(focusedMemory+2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
        Core.reset();
        showCode();
        showMemory();  
        display();
        Core.isOver=false;
        jRun.setEnabled(true);
        jPause.setEnabled(false);
        jStep.setEnabled(true);
        jReset.setEnabled(true);
    }//GEN-LAST:event_jResetActionPerformed

    private void jStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStepActionPerformed
        // TODO add your handling code here:
        Core.step();
        showCode();
        showMemory();  
        display();
        if (Core.isOver)
        {
            JOptionPane.showMessageDialog(this,Core.message,"运行结果",JOptionPane.INFORMATION_MESSAGE);
            jRun.setEnabled(false);
            jPause.setEnabled(false);
            jStep.setEnabled(false);
            jReset.setEnabled(true);            
        }
        else
        {
            jRun.setEnabled(true);
            jPause.setEnabled(false);
            jStep.setEnabled(true);
            jReset.setEnabled(true);       
        }
    }//GEN-LAST:event_jStepActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRunActionPerformed
        // TODO add your handling code here:
        jRun.setEnabled(false);
        jPause.setEnabled(true);
        jStep.setEnabled(false);
        jReset.setEnabled(false); 
        jMenuItem1.setEnabled(false);
        if (jComboBox1.getSelectedIndex()==0)
            time=new Timer(1000,this);
        if (jComboBox1.getSelectedIndex()==1)
            time=new Timer(500,this);
        if (jComboBox1.getSelectedIndex()==2)
            time=new Timer(200,this);
        if (jComboBox1.getSelectedIndex()==3)
            time=new Timer(100,this);
        time.start();
    }//GEN-LAST:event_jRunActionPerformed

    @Override
    public void actionPerformed(ActionEvent e)
    {
        if (Core.isOver)
        {
            JOptionPane.showMessageDialog(this,Core.message,"运行结果",JOptionPane.INFORMATION_MESSAGE);
            jRun.setEnabled(false);
            jPause.setEnabled(false);
            jStep.setEnabled(false);
            jReset.setEnabled(true);
            jMenuItem1.setEnabled(true);
            time.stop();
        }
        else
        {
            Core.step();
            showCode();
            showMemory();  
            display();            
        }
    }
    
    private void jPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPauseActionPerformed
        // TODO add your handling code here:
        time.stop();
        jRun.setEnabled(true);
        jPause.setEnabled(false);
        jStep.setEnabled(true);
        jReset.setEnabled(true);
        jMenuItem1.setEnabled(true);
    }//GEN-LAST:event_jPauseActionPerformed
    
    void showCode()
    {
        Document doc=jTextPane1.getDocument();
        try
        { 
            doc.remove(0,doc.getLength());
        }
        catch (BadLocationException ex)
        {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleAttributeSet attrSet=new SimpleAttributeSet();
        focusedCode=-1;
        Core.addinstuction=false;
        try
        {
            for (int i=1;i<=Assembler.lineNum;i++)
            {
                String tmp=Assembler.binaryCode[i];
                while (tmp.length()<12)
                    tmp=tmp+" ";
                String line="0x"+Assembler.toBigEndian(Assembler.codeAddress[i])+": "+tmp+" | "+Assembler.originCode[i]+"\n";
                StyleConstants.setForeground(attrSet,Color.black);
                if (Assembler.codeAddress[i]==Core.D_addr&&Assembler.binaryCode[i].length()>0)
                {
                    StyleConstants.setForeground(attrSet,Color.blue);
                    focusedCode=doc.getLength();
                }                 
                if (Assembler.codeAddress[i]==Core.E_addr&&Assembler.binaryCode[i].length()>0)
                {
                    StyleConstants.setForeground(attrSet,new Color(51,153,0));
                    focusedCode=doc.getLength();
                }
                if (Assembler.codeAddress[i]==Core.M_addr&&Assembler.binaryCode[i].length()>0)
                {
                    StyleConstants.setForeground(attrSet,new Color(255,102,0));
                    focusedCode=doc.getLength();
                }
                if (Assembler.codeAddress[i]==Core.W_addr&&Assembler.binaryCode[i].length()>0)
                {
                    StyleConstants.setForeground(attrSet,new Color(204,0,204));
                    focusedCode=doc.getLength();
                    Core.addinstuction=true;
                }
                if (Assembler.codeAddress[i]==Core.F_addr&&Assembler.binaryCode[i].length()>0)
                {
                    StyleConstants.setForeground(attrSet,Color.red);
                    focusedCode=doc.getLength();
                }
                doc.insertString(doc.getLength(),line,attrSet);
            }
        }
        catch (BadLocationException ex)
        {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jTextPane1.setDocument(doc);
        jTextPane1.setSelectionStart(focusedCode);
        jTextPane1.setSelectionEnd(focusedCode+2);
        jTextPane1.setSelectionEnd(focusedCode);   
    }
    
    void showMemory()
    {
        String line="";
        for (int i=0;i<Core.memory.length;i++)
        {
            if ((i&15)==0)
                line+="0x"+Assembler.toBigEndian((long)i).substring(5) +": ";
            line+=Integer.toHexString(Core.memory[i]/16);
            line+=Integer.toHexString(Core.memory[i]%16);
            line+=" ";
            if ((i&15)==15)
                line+="\n";
        }
        jTextArea1.setText(line);
        jTextArea1.setSelectionStart(focusedMemory);
        jTextArea1.setSelectionEnd(focusedMemory+2);
        jButton1.setEnabled(true);
    }
    
    int boolToInt(boolean flag)
    {
        if (flag) return 1;
        return 0;
    }
    
    String toStat(int stat)
    {
        if (stat==1) return "STA";
        if (stat==2) return "BUB";
        return "AOK";
    }
    
    String toReg(int reg)
    {
        if (reg==0) return "%eax";
        if (reg==1) return "%ecx";
        if (reg==2) return "%edx";
        if (reg==3) return "%ebx";
        if (reg==4) return "%esp";
        if (reg==5) return "%ebp";
        if (reg==6) return "%esi";
        if (reg==7) return "%edi";
        return "none";
    }
    
    void display()
    {
        jcycle.setText(""+Core.cycle);
        jinstruction.setText(""+Core.instruction);
        if (Core.instruction==0) jCPI.setText("N/A");
        else
        {
            String tmp=""+(double)Core.cycle/Core.instruction;
            while (tmp.length()>5)
                tmp=tmp.substring(0,tmp.length()-1);
            jCPI.setText(tmp);
        }
        jZF.setText(""+boolToInt(Core.ZF));
        jSF.setText(""+boolToInt(Core.SF));
        jOF.setText(""+boolToInt(Core.OF));
        jM_Cnd.setText(""+boolToInt(Core.M_Cnd));
        jeax.setText("0x"+Assembler.toBigEndian(Core.r[0]));
        jecx.setText("0x"+Assembler.toBigEndian(Core.r[1]));
        jedx.setText("0x"+Assembler.toBigEndian(Core.r[2]));
        jebx.setText("0x"+Assembler.toBigEndian(Core.r[3]));
        jesp.setText("0x"+Assembler.toBigEndian(Core.r[4]));
        jebp.setText("0x"+Assembler.toBigEndian(Core.r[5]));
        jesi.setText("0x"+Assembler.toBigEndian(Core.r[6]));
        jedi.setText("0x"+Assembler.toBigEndian(Core.r[7]));
        jF_stat.setText(toStat(Core.F_stat));
        jD_stat.setText(toStat(Core.D_stat));
        jE_stat.setText(toStat(Core.E_stat));
        jM_stat.setText(toStat(Core.M_stat));
        jW_stat.setText(toStat(Core.W_stat));
        jF_predPC.setText("0x"+Assembler.toBigEndian(Core.F_predPC));
        jPC.setText("0x"+Assembler.toBigEndian(Core.PC));
        jD_icode.setText(Integer.toHexString(Core.D_icode));
        jE_icode.setText(Integer.toHexString(Core.E_icode));
        jM_icode.setText(Integer.toHexString(Core.M_icode));
        jW_icode.setText(Integer.toHexString(Core.W_icode));
        jD_ifun.setText(Integer.toHexString(Core.D_ifun));
        jE_ifun.setText(Integer.toHexString(Core.E_ifun));
        jD_rA.setText(toReg(Core.D_rA));
        jD_rB.setText(toReg(Core.D_rB));
        jE_dstE.setText(toReg(Core.E_dstE));
        jE_dstM.setText(toReg(Core.E_dstM));
        jE_srcA.setText(toReg(Core.E_srcA));
        jE_srcB.setText(toReg(Core.E_srcB));
        jM_dstE.setText(toReg(Core.M_dstE));
        jM_dstM.setText(toReg(Core.M_dstM));
        jW_dstE.setText(toReg(Core.W_dstE));
        jW_dstM.setText(toReg(Core.W_dstM));
        jD_valC.setText("0x"+Assembler.toBigEndian(Core.D_valC));
        jD_valP.setText("0x"+Assembler.toBigEndian(Core.D_valP));
        jE_valC.setText("0x"+Assembler.toBigEndian(Core.E_valC));
        jE_valA.setText("0x"+Assembler.toBigEndian(Core.E_valA));
        jE_valB.setText("0x"+Assembler.toBigEndian(Core.E_valB));
        jM_valE.setText("0x"+Assembler.toBigEndian(Core.M_valE));
        jM_valA.setText("0x"+Assembler.toBigEndian(Core.M_valA));
        jW_valE.setText("0x"+Assembler.toBigEndian(Core.W_valE));
        jW_valM.setText("0x"+Assembler.toBigEndian(Core.W_valM));              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCPI;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jD_icode;
    private javax.swing.JLabel jD_ifun;
    private javax.swing.JLabel jD_rA;
    private javax.swing.JLabel jD_rB;
    private javax.swing.JLabel jD_stat;
    private javax.swing.JLabel jD_valC;
    private javax.swing.JLabel jD_valP;
    private javax.swing.JLabel jE_dstE;
    private javax.swing.JLabel jE_dstM;
    private javax.swing.JLabel jE_icode;
    private javax.swing.JLabel jE_ifun;
    private javax.swing.JLabel jE_srcA;
    private javax.swing.JLabel jE_srcB;
    private javax.swing.JLabel jE_stat;
    private javax.swing.JLabel jE_valA;
    private javax.swing.JLabel jE_valB;
    private javax.swing.JLabel jE_valC;
    private javax.swing.JLabel jF_predPC;
    private javax.swing.JLabel jF_stat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jM_Cnd;
    private javax.swing.JLabel jM_dstE;
    private javax.swing.JLabel jM_dstM;
    private javax.swing.JLabel jM_icode;
    private javax.swing.JLabel jM_stat;
    private javax.swing.JLabel jM_valA;
    private javax.swing.JLabel jM_valE;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel jOF;
    private javax.swing.JLabel jPC;
    private javax.swing.JButton jPause;
    private javax.swing.JButton jReset;
    private javax.swing.JButton jRun;
    private javax.swing.JLabel jSF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jStep;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jW_dstE;
    private javax.swing.JLabel jW_dstM;
    private javax.swing.JLabel jW_icode;
    private javax.swing.JLabel jW_stat;
    private javax.swing.JLabel jW_valE;
    private javax.swing.JLabel jW_valM;
    private javax.swing.JLabel jZF;
    private javax.swing.JLabel jcycle;
    private javax.swing.JLabel jeax;
    private javax.swing.JLabel jebp;
    private javax.swing.JLabel jebx;
    private javax.swing.JLabel jecx;
    private javax.swing.JLabel jedi;
    private javax.swing.JLabel jedx;
    private javax.swing.JLabel jesi;
    private javax.swing.JLabel jesp;
    private javax.swing.JLabel jinstruction;
    // End of variables declaration//GEN-END:variables
}
